export const markets = { all: '所有市场', US: '美国', AE: '阿联酋', GB: '英国', DE: '德国' };
export const stages = ['新线索', '需求确认', '已约试驾', '方案洽谈', '已成交', '售后维护'];
export const scenarios = [
  {id:'intake',icon:'users',title:'把咨询接成可跟进的线索',subtitle:'梳理已有事实和未知，准备追问与销售交接',label:'线索识别与交接',prompt:'整理这位客户的已有资料、关键未知、建议追问和销售交接卡，不从联系方式推测身份。',color:'sage',deliver:'需求摘要 + 追问 + 交接卡'},
  {id:'relationship',icon:'heart',title:'找到下一次有理由的联系',subtitle:'结合生命周期与服务状态，安排客户关系经营',label:'客户关系经营',prompt:'整理这位客户的关系状态、需要核实的变化和下一次联系计划，有未结投诉时先交给售后。',color:'rose',deliver:'关系健康卡 + 联系计划'},
  {id:'review',icon:'target',title:'让复盘真正改变下一轮活动',subtitle:'对齐联系、接受与预约，找出需要补证的环节',label:'活动复盘与调整',prompt:'根据当前工作区业务记录复盘活动，区分发送、客户接受、预约与到店，列出资料缺口与下一轮调整建议；没有成本数据时不计算回报率。',color:'sand',deliver:'漏斗复盘 + 下一轮行动表'},
  {id:'regional',icon:'globe',title:'看清每家店卡在哪里',subtitle:'汇总同口径记录，给出带责任人与期限的行动',label:'跨店经营简报',prompt:'汇总当前各门店的工作进展、待回复、预约与服务问题，区分数据缺失和经营异常，给出责任人与期限明确的行动清单。',color:'lavender',deliver:'跨店简报 + 负责人行动清单'},
  { id: 'followup', icon: 'message', title: '让跟进更有温度', subtitle: '读懂客户记忆，写出刚刚好的下一句话', label: '个性化跟进', prompt: '为 Sarah 生成一条试驾后的 WhatsApp 跟进，回应她对家庭充电的顾虑。', color: 'sage', deliver: '客户洞察 + 双语话术' },
  { id: 'quote', icon: 'car', title: '让好车遇到对的人', subtitle: '匹配预算与用车需求，准备有说服力的方案', label: '选车与报价', prompt: '为 Marcus 准备一份选车与报价方案，考虑他的通勤、预算和置换需求。', color: 'sand', deliver: '车型推荐 + 购车费用表' },
  { id: 'campaign', icon: 'megaphone', title: '让每一次曝光有回应', subtitle: '从目标客群到内容，把活动准备得更周全', label: '营销活动', prompt: '为迪拜门店策划周末 SUV 试驾活动，生成英文与阿拉伯文邀约及跟进计划。', color: 'lavender', deliver: '活动简报 + 多语言内容' },
  { id: 'testdrive', icon: 'calendar', title: '把心动变成一次试驾', subtitle: '结合当地时间与客户偏好，准备试驾邀约', label: '试驾邀约', prompt: '为 Sarah 准备家庭试驾邀约，包括儿童座椅、充电演示与预约确认。', color: 'sage', deliver: '邀约话术 + 试驾检查清单' },
  { id: 'aftersales', icon: 'heart', title: '交付，是关系的开始', subtitle: '新车使用、保养提醒与转介绍，持续陪伴', label: '售后关怀', prompt: '为 Linda 生成交付后的关怀消息，了解用车体验，并确认里程和保养需求。', color: 'rose', deliver: '关怀话术 + 服务检查清单' }
];

const ago = (days) => new Date(Date.now() - days * 86400000).toISOString();
export function seedState() {
  return {
    version: 3,
    customers: [
      { id: 'c1', name: 'Sarah Johnson', initials: 'SJ', color: 'peach', market: 'US', city: 'Austin, TX', timezone: 'America/Chicago', language: 'en', currency: 'USD', role: '家庭增购 · 产品设计师', stage: '需求确认', intent: 92, budget: [45000, 55000], vehicle: 'Tesla Model Y', channel: 'WhatsApp', contact: '+1 (512) 555-0142', email: 'sarah@example.com', source: 'Meta Lead Ads', owner: 'Alex Chen', lastContact: ago(3), consent: { WhatsApp: true, Email: true }, need: '一家四口的日常通勤与周末出游，关注后排空间和家庭充电。', concern: '公寓充电桩尚未确认，希望了解安装条件；需要放下两个儿童座椅。', next: '确认家庭试驾时间，并准备充电方案', memories: [{ text: '两个孩子，分别 3 岁和 6 岁；希望试装儿童座椅。', source: '销售记录 · 需求沟通' }, { text: '预算 $45,000–55,000，计划两周内购车。', source: 'Meta 表单 · 客户填写' }, { text: '住公寓，有固定车位，物业能否安装充电桩待确认。', source: 'WhatsApp · 客户反馈' }], tags: ['家庭用车', '充电顾虑', '两周内购车'], timeline: [{ title: '完成需求沟通', body: '关注 Model Y 空间，计划和家人一起到店。', at: ago(3) }, { title: '从 Meta 广告留资', body: '已同意通过 WhatsApp 接收购车沟通。', at: ago(6) }] },
      { id: 'c2', name: 'Omar Al Mansoori', initials: 'OA', color: 'sage', market: 'AE', city: 'Dubai', timezone: 'Asia/Dubai', language: 'ar', currency: 'AED', role: '企业采购 · 车队负责人', stage: '方案洽谈', intent: 88, budget: [180000, 230000], vehicle: 'Toyota Land Cruiser', channel: 'WhatsApp', contact: '+971 50 555 0148', email: 'omar@example.com', source: 'Google Search', owner: 'Alex Chen', lastContact: ago(9), consent: { WhatsApp: true, Email: true }, need: '采购 3 台 SUV 用于企业接待，偏好 GCC 规格与长期服务支持。', concern: '需核实 GCC 规格、保修范围、批量交付日期及 VAT 发票。', next: '确认 3 台车的交期与企业采购条件', memories: [{ text: '首批计划采购 3 台，每台预算 AED 180,000–230,000。', source: '电话纪要 · 销售确认' }, { text: '沟通偏好阿拉伯语，报价文件需要英文。', source: 'WhatsApp · 客户偏好' }, { text: '要求 GCC 规格与本地保修；目前尚未收到确认文件。', source: '采购需求 · 待核实' }], tags: ['企业采购', 'GCC 规格', '批量订单'], timeline: [{ title: '收到企业采购需求', body: '需发送配置、规格证明和可交付时间。', at: ago(9) }] },
      { id: 'c3', name: 'Marcus Reed', initials: 'MR', color: 'blue', market: 'US', city: 'Los Angeles, CA', timezone: 'America/Los_Angeles', language: 'en', currency: 'USD', role: '首次换车 · 软件工程师', stage: '方案洽谈', intent: 84, budget: [33000, 40000], vehicle: 'Toyota RAV4 Hybrid', channel: 'Email', contact: '+1 (213) 555-0117', email: 'marcus@example.com', source: 'Website Chat', owner: 'Alex Chen', lastContact: ago(8), consent: { WhatsApp: false, Email: true }, need: '每日通勤约 45 英里，比较混动车型的用车成本，考虑置换。', concern: '关注月供和落地价，旧车估值与金融审批尚未完成。', next: '发送费用透明的混动方案，预约旧车评估', memories: [{ text: '2018 Honda Accord，约 80,000 英里，置换估值待检测。', source: '网站咨询 · 客户提供' }, { text: '每日通勤 45 英里，偏好混动，无固定充电位。', source: '销售记录 · 需求沟通' }], tags: ['混动通勤', '置换', '关注月供'], timeline: [{ title: '进入方案比较阶段', body: '希望先了解费用，再安排试驾。', at: ago(8) }] },
      { id: 'c4', name: 'Fatima Hassan', initials: 'FH', color: 'lavender', market: 'AE', city: 'Abu Dhabi', timezone: 'Asia/Dubai', language: 'en', currency: 'AED', role: '家庭首购 · 教育工作者', stage: '需求确认', intent: 76, budget: [100000, 130000], vehicle: 'Hyundai Tucson', channel: 'WhatsApp', contact: '+971 50 555 0192', email: 'fatima@example.com', source: 'Instagram', owner: 'Mia Wang', lastContact: ago(8), consent: { WhatsApp: true, Email: false }, need: '家庭第一台 SUV，关注泊车、儿童座椅与售后服务。', concern: '希望试驾验证泊车体验，保修条款待门店确认。', next: '安排周末 SUV 试驾', memories: [{ text: '工作日忙，周末下午方便到店。', source: 'Instagram · 客户反馈' }], tags: ['家庭首购', 'SUV', '周末试驾'], timeline: [{ title: '确认预算与用途', body: '对 Tucson 感兴趣。', at: ago(8) }] },
      { id: 'c5', name: 'Emma Wilson', initials: 'EW', color: 'rose', market: 'GB', city: 'Manchester', timezone: 'Europe/London', language: 'en', currency: 'GBP', role: '电动化换购 · 顾问', stage: '新线索', intent: 65, budget: [38000, 45000], vehicle: 'Kia EV6', channel: 'Email', contact: '+44 7700 900123', email: 'emma@example.com', source: 'Google Search', owner: 'Mia Wang', lastContact: ago(10), consent: { WhatsApp: false, Email: true }, need: '寻找右舵纯电动车，希望了解家庭充电与长途出行。', concern: '英国现车与本地售价尚未接入，不可沿用美国报价。', next: '确认英国右舵车源和充电需求', memories: [{ text: '需要英国右舵车型，不接受其他市场配置替代。', source: '客户表单 · 需求' }], tags: ['右舵车型', '家充', '英国市场'], timeline: [{ title: '新增网站线索', body: '待确认购车时间。', at: ago(10) }] },
      { id: 'c6', name: 'David Chen', initials: 'DC', color: 'blue', market: 'US', city: 'San Jose, CA', timezone: 'America/Los_Angeles', language: 'en', currency: 'USD', role: '新车车主 · 研发经理', stage: '已成交', intent: 100, budget: [48000, 55000], vehicle: 'Kia EV6', channel: 'Email', contact: '+1 (408) 555-0125', email: 'david@example.com', source: 'Referral', owner: 'Alex Chen', lastContact: ago(8), consent: { WhatsApp: false, Email: true }, need: '已提车，需熟悉充电、手机应用与长途出行。', concern: '想确认公司充电桩兼容性。', next: '完成新车使用回访', memories: [{ text: '已交付 Kia EV6，公司有公共充电位。', source: '交付清单 · 销售记录' }], tags: ['已交付', '充电指导', '转介绍潜力'], timeline: [{ title: '新车交付', body: '已完成交车说明，待使用回访。', at: ago(8) }] },
      { id: 'c7', name: 'Linda Garcia', initials: 'LG', color: 'sand', market: 'US', city: 'Miami, FL', timezone: 'America/New_York', language: 'en', currency: 'USD', role: '存量车主 · 小企业主', stage: '售后维护', intent: 100, budget: [35000, 42000], vehicle: 'Toyota RAV4 Hybrid', channel: 'WhatsApp', contact: '+1 (305) 555-0176', email: 'linda@example.com', source: 'Walk-in', owner: 'Mia Wang', lastContact: ago(15), consent: { WhatsApp: true, Email: true }, need: '交付后约 45 天，关注日常使用和第一次保养。', concern: '实际里程未知，需要依据手册核定保养时间。', next: '询问使用体验和当前里程', memories: [{ text: '约 45 天前交付，首保计划待当前里程确认。', source: '交付记录 · 门店' }], tags: ['售后关怀', '里程待确认', '老客户'], timeline: [{ title: '交付后首次关怀', body: '总体体验良好，希望提前收到保养提醒。', at: ago(15) }] },
      { id: 'c8', name: 'Lucas Martin', initials: 'LM', color: 'sage', market: 'DE', city: 'Berlin', timezone: 'Europe/Berlin', language: 'de', currency: 'EUR', role: '新能源意向 · 自由职业者', stage: '需求确认', intent: 68, budget: [45000, 50000], vehicle: 'Volkswagen ID.4', channel: 'Email', contact: '+49 1512 3456789', email: 'lucas@example.com', source: 'Website', owner: 'Mia Wang', lastContact: ago(12), consent: { WhatsApp: false, Email: false }, need: '对比纯电 SUV，关注实际使用成本。', concern: '未取得营销联系授权，需要先补充授权记录。', next: '等待客户主动咨询或补充联系授权', memories: [{ text: '尚未取得营销邮件和 WhatsApp 联系授权。', source: '授权记录 · 网站表单' }], tags: ['纯电 SUV', '待授权', '德国市场'], timeline: [{ title: '新增询价线索', body: '仅记录询价，营销授权未勾选。', at: ago(12) }] }
    ],
    vehicles: [
      { id: 'v1', name: 'Tesla Model Y', trim: 'Long Range · 2026', market: 'US', currency: 'USD', price: 49990, stock: 4, energy: '纯电', type: 'SUV', location: 'Austin', color: '#bdc8c8', detail: '5 座 · 家庭空间 · 全景玻璃车顶', checked: '示例库存，实际配置和交期需确认' },
      { id: 'v2', name: 'Toyota RAV4 Hybrid', trim: 'XLE · 2026', market: 'US', currency: 'USD', price: 37950, stock: 7, energy: '混动', type: 'SUV', location: 'Los Angeles', color: '#8e9d95', detail: '5 座 · 混动通勤 · 城市与周末出行', checked: '示例库存，税费和金融条件待核实' },
      { id: 'v3', name: 'Kia EV6', trim: 'Wind · 2026', market: 'US', currency: 'USD', price: 46900, stock: 3, energy: '纯电', type: 'Crossover', location: 'San Jose', color: '#acaead', detail: '5 座 · 纯电跨界 · 充电条件需匹配', checked: '示例库存，充电配置和交期待确认' },
      { id: 'v4', name: 'Toyota Land Cruiser', trim: 'GXR · 2026', market: 'AE', currency: 'AED', price: 219900, stock: 3, energy: '燃油', type: 'SUV', location: 'Dubai', color: '#d5cfc1', detail: '企业接待 · 多用途 SUV · GCC 规格待验证', checked: 'GCC 认证、本地保修和批量交期待确认' },
      { id: 'v5', name: 'Hyundai Tucson', trim: 'Premium · 2026', market: 'AE', currency: 'AED', price: 119900, stock: 5, energy: '燃油', type: 'SUV', location: 'Abu Dhabi', color: '#80959b', detail: '5 座 · 家庭首购 · 城市泊车', checked: '示例库存，本地配置和保修待确认' },
      { id: 'v6', name: 'Volkswagen ID.4', trim: 'Pro · 2026', market: 'DE', currency: 'EUR', price: 46900, stock: 2, energy: '纯电', type: 'SUV', location: 'Berlin', color: '#98a5b2', detail: '5 座 · 电动 SUV · 欧盟市场', checked: '示例价格，含税口径和交期待确认' }
    ],
    tasks: [], artifacts: [],
    automations: [
      { id: 'a1', name: '高意向客户 · 每周跟进', description: '结合最近沟通，为高意向客户准备一条有价值的跟进。', segment: 'hot', kind: 'followup', cadence: 7, hour: 10, enabled: true, lastRun: null, createdAt: ago(8) },
      { id: 'a2', name: '交付之后 · 用车关怀', description: '了解真实用车体验，确认里程后再准备服务建议。', segment: 'owners', kind: 'aftersales', cadence: 30, hour: 11, enabled: true, lastRun: null, createdAt: ago(8) },
      { id: 'a3', name: '沉睡线索 · 重新连接', description: '用新的车型信息重新开启对话，尊重客户的联系偏好。', segment: 'dormant', kind: 'followup', cadence: 14, hour: 14, enabled: false, lastRun: null, createdAt: ago(8) }
    ],
    campaigns: [{ id: 'p1', title: 'Dubai · 周末 SUV 体验日', market: 'AE', channel: 'WhatsApp + Instagram', audience: '家庭 SUV 意向客户', goal: '让合适的客户走进展厅', status: '筹备中', color: 'sand' }, { id: 'p2', title: 'Your next chapter, electric.', market: 'US', channel: 'Email + Meta', audience: '新能源与家庭增购客户', goal: '以真实用车场景开启电动出行', status: '内容准备', color: 'sage' }, { id: 'p3', title: 'A little care. A long way.', market: 'US', channel: 'Email + WhatsApp', audience: '已交付的新车车主', goal: '让车主关怀成为长期关系', status: '待排期', color: 'lavender' }],
    knowledge: [{ id: 'k1', title: '品牌与沟通风格', category: '品牌指南', body: '语气友好、具体、简洁；每条消息只保留一个明确行动。引用已确认的客户需求；不制造虚假库存紧迫感，不承诺未经审批的折扣。', updatedAt: ago(1) }, { id: 'k2', title: '跨市场报价检查清单', category: '销售手册', body: '核对销售地区、币种、左右舵、当地配置、税费口径与交期。旧车评估、贷款利率及补贴均需独立确认；禁止把其他市场车源直接用作当地报价。', updatedAt: ago(3) }, { id: 'k3', title: '客户联系与偏好', category: '工作规则', body: '自动化生成内容前校验客户渠道授权、当地时间与联系间隔。退订后暂停营销跟进。所有自动化结果进入人工审核，连接真实服务后才能发送。', updatedAt: ago(2) }],
    automationLog: [], settings: { name: 'Atlas Motors', operator: 'Alex Chen', role: '销售顾问', minGapDays: 7 }
  };
}
