import {markets} from './data.js';
import {PERSONAS,WORKFLOWS,dashboardData,marketFacts,visibleDeliveries,updateDelivery,prepareBriefing,saveMCPConfiguration} from './experience-model.js';
import {isArtifactCurrent} from './cowork.js';

export function createExperienceUI(api){
  const {esc,i,btn}=api,state=()=>api.state(),ui=()=>api.ui();
  const role=()=>PERSONAS[ui().role]||PERSONAS.sales;
  const workflows=()=>WORKFLOWS.filter(w=>w.role===ui().role);
  const marketSelect=()=>`<select class="select" data-change="market" aria-label="工作范围">${Object.entries(markets).map(([id,label])=>`<option value="${id}" ${ui().market===id?'selected':''}>${label}</option>`).join('')}</select>`;
  const stamp=at=>new Date(at).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
  const actionFor=r=>r.type==='chat'?'chat-select':r.type==='generation'?'select-task':'cw-open';
  function rolePicker(){return `<label class="xp-role-picker"><span>当前角色</span><select aria-label="切换工作角色" data-change="persona">${Object.entries(PERSONAS).map(([id,r])=>`<option value="${id}" ${ui().role===id?'selected':''}>${r.label}</option>`).join('')}</select></label>`;}
  function tabs(){return `<nav class="ux-tabs xp-work-tabs" aria-label="工作台视图">${[['desk','工作流'],['customers','客户与画像'],['inventory','车源与方案'],['campaigns','营销活动'],['regional','经营概览'],['inbox','行动待办'],['deliverables','全部成果']].map(([id,label])=>`<a href="#${id}" ${ui().page===id?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;}
  function workflowCards(){return `<div class="xp-workflows">${workflows().map((w,index)=>`<button class="xp-workflow" data-act="xp-workflow" data-id="${w.id}"><div class="row between"><span class="xp-symbol">${i(w.icon)}</span><span class="xp-number">0${index+1}</span></div><h3>${w.title}</h3><p>${w.steps[0]} → ${w.steps.at(-1)}</p><div class="xp-workflow-output">${i('doc')}<span>${w.output}</span>${i('arrow')}</div></button>`).join('')}</div>`;}
  function home(){
    const d=dashboardData(state(),ui().role,ui().market),inbox=visibleDeliveries(state(),ui().role,ui().market).filter(x=>!x.archived),unread=inbox.filter(x=>!x.read);
    const quick=ui().role==='sales'?[['记录客户沟通','chat-profile','message'],['新增销售线索','ux-lead','plus']]:ui().role==='marketing'?[['创建营销活动','new-campaign','plus'],['导入客户资料','ux-import','users']]:[['查看经营概览','xp-regional','grid'],['准备工作简报','xp-brief','doc']];
    return `<div class="xp-dashboard"><div class="xp-dashboard-heading"><div><span class="eyebrow">PERSONAL INTELLIGENCE / ${role().en}</span><h1>${esc(state().settings.operator)}，今天从这里开始。</h1><p>${role().headline}</p></div>${marketSelect()}</div>${api.homeConversation()}<div class="xp-metrics">${d.metrics.map(([label,value])=>`<div><span>${label}</span><strong>${String(value).padStart(2,'0')}</strong><small>当前范围的工作区记录</small></div>`).join('')}<a href="#proactive"><span>AI 新来信</span><strong>${String(unread.length).padStart(2,'0')}</strong><small>已经备好的工作 ${i('arrow')}</small></a></div><div class="xp-dashboard-grid"><section class="xp-priority"><div class="xp-section-head"><div><span class="eyebrow">YOUR NEXT MOVES</span><h2>需要你推进</h2></div><span class="badge gray">${d.priorities.length} 项待处理</span></div>${d.priorities.length?d.priorities.slice(0,5).map((t,n)=>`<button class="xp-priority-row" data-act="${actionFor(t)}" data-id="${esc(t.key)}"><span class="xp-order">${String(n+1).padStart(2,'0')}</span><div><strong>${esc(t.title)}</strong><p>${esc(t.next||({blocked:'需要处理：检查模型连接或更新资料后继续。',review:'已有成果或待办，等待你查看并推进。',running:'Cowork 正在准备成果。',active:'继续补充资料，确定下一步。'}[t.id]))}</p><small>${esc(t.owner||state().settings.operator)} · ${esc(t.label)}</small></div>${i('arrow')}</button>`).join(''):`<div class="xp-empty"><span>${i('checkCircle')}</span><h3>当前没有分配给你的待办</h3><p>从下方工作流开始，或直接和 Cowork 讨论。</p></div>`}<a class="xp-panel-footer" href="#desk">查看工作台全部任务 ${i('arrow')}</a></section><aside class="xp-today-side"><section class="xp-mail-preview"><div class="row between"><h3>最近 AI 来信</h3><a href="#proactive">${i('arrow')}</a></div>${inbox.length?inbox.slice(0,2).map(x=>`<button data-act="xp-delivery" data-id="${x.id}"><span class="xp-unread ${x.read?'read':''}"></span><div><strong>${esc(x.title)}</strong><small>${esc(x.source)} · ${stamp(x.at)}</small></div></button>`).join(''):'<p>简报和定时任务备好后，会送到这里。</p>'}</section></aside></div><div class="xp-section-head xp-launch-heading"><div><h2>${role().workTitle}</h2><p>选择工作流，在中间查看成果，在右侧与 Cowork 协作。</p></div><div class="row">${quick.map(([label,act,icon])=>btn(label,act,icon,'sm')).join('')}</div></div>${workflowCards()}<p class="xp-data-note">角色切换用于查看不同工作视角；当前数据保存在本浏览器，初始记录含示例。</p></div>`;
  }
  function desk(){
    const candidates=state().conversations.filter(c=>c.tracked&&(c.persona||'sales')===ui().role&&(ui().market==='all'||(c.market||state().customers.find(x=>x.id===c.customerId)?.market||c.customerId?.split(':')[1])===ui().market));
    const recent=candidates.find(c=>c.id===ui().conversationId)||candidates[0];
    return `<div class="xp-desk-intro"><div class="page-heading"><div><span class="eyebrow">WORKBENCH / ${role().en}</span><h1>工作台</h1><p>打开一项工作，在中间编辑成果，在右侧与 Cowork 一起完善。</p></div>${btn('新建任务','ux-task-new','plus','soft')}</div>${tabs()}${recent?`<section class="wb-resume"><span>继续上次的工作</span><div><h2>${esc(recent.goal||recent.title)}</h2><p>成果和对话都在原来的位置。</p></div>${btn('打开成果工作区','chat-select','arrow','primary',`data-id="${recent.id}"`)}</section>`:''}<details class="wb-workflow-library" ${!recent?'open':''}><summary>从常用场景开始一项新工作 <span>${role().workTitle}</span></summary>${workflowCards()}</details></div>${api.desk()}`;
  }
  function regional(){return `<div class="page-heading"><div><span class="eyebrow">REGIONAL INTELLIGENCE</span><h1>经营概览</h1><p>先核对范围和口径，再制定门店行动。</p></div>${btn('开始经营诊断','xp-workflow','spark','primary','data-id="regional-review"')}</div><div class="xp-source-notice">当前按市场汇总本地客户与工作记录。缺少门店编号、销售目标和订单流水，门店排名与销售达成率待接入后提供。</div><div class="table-wrap"><table><thead><tr><th>市场</th><th>客户记录</th><th>新线索</th><th>14 天未联系潜客</th><th>未结服务问题</th><th>预约回执</th><th></th></tr></thead><tbody>${Object.entries(markets).filter(([id])=>id!=='all'&&(ui().market==='all'||ui().market===id)).map(([id,label])=>{const f=marketFacts(state(),id);return `<tr><td>${label}</td><td>${f.customers.length}</td><td>${f.leads.length}</td><td>${f.dormant.length}</td><td>${f.issues.length}</td><td>${f.reservations}</td><td>${btn('制定行动计划','xp-workflow','arrow','sm',`data-id="store-action" data-market="${id}"`)}</td></tr>`;}).join('')}</tbody></table></div><div class="xp-section-head"><h2>从经营记录，走到执行反馈</h2>${marketSelect()}</div><div class="xp-workflows">${[['01','诊断有来源','报告引用工作记录；缺失数据显式列出。'],['02','行动有负责人','在工作台安排动作、负责人和截止时间。'],['03','结果有证据','回报实际执行情况，区分任务完成与业绩结果。']].map(([n,title,body])=>`<article class="xp-workflow"><span class="eyebrow">${n}</span><h3>${title}</h3><p>${body}</p></article>`).join('')}</div>`;}
  function deliveryBody(d){
    const a=state().artifacts.find(a=>a.id===d.artifactId),stale=a&&!isArtifactCurrent(state(),a);
    return `<article class="xp-mail-detail"><div class="xp-mail-tools">${btn(d.read?'标为未读':'标为已读','xp-mail-state',null,'sm',`data-id="${d.id}" data-mode="${d.read?'unread':'read'}"`)}${btn(d.archived?'移回收件箱':'归档','xp-mail-state',null,'sm',`data-id="${d.id}" data-mode="${d.archived?'restore':'archive'}"`)}</div><span class="eyebrow">${d.kind==='brief'?'WORK BRIEF':d.kind==='failure'?'ACTION REQUIRED':'DELIVERED FOR REVIEW'}</span><h2>${esc(d.title)}</h2><div class="xp-mail-byline"><span class="xp-symbol">${i('spark')}</span><div><strong>Motive Cowork → ${role().label}</strong><small>${esc(d.source)} · ${stamp(d.at)}</small></div></div>${stale?'<div class="xp-source-notice">客户资料已变化，这份附件是历史版本。打开工作台后依据最新资料重新准备。</div>':''}${d.kind==='brief'?(d.sections||[]).map(s=>`<section><h3>${esc(s.label)}</h3><p>${esc(s.text)}</p></section>`).join(''):`<p>${esc(d.preview)}</p>${a?`<div class="xp-mail-attachment">${i('doc')}<div><strong>${esc(a.title)}</strong><small>${stale?'资料已更新':a.status==='review'?'待审核草稿':'已保存成果'}${d.posterId?' · 含活动海报':''}</small></div></div>`:''}`}<div class="xp-mail-next">${btn(d.taskId?'打开工作台继续':'据此制定下一步','xp-delivery-work','arrow','primary',`data-id="${d.id}"`)}</div></article>`;
  }
  function proactive(){
    const all=visibleDeliveries(state(),ui().role,ui().market),filter=ui().deliveryFilter||'inbox';
    const list=all.filter(d=>filter==='archive'?d.archived:!d.archived&&(filter!=='unread'||!d.read)&&(filter!=='failure'||d.kind==='failure'));
    const current=list.find(x=>x.id===ui().deliveryId);
    return `<div class="page-heading"><div><span class="eyebrow">PROACTIVE WORKFLOW</span><h1>AI 来信</h1><p>工作备好后，直接交到你面前。打开成果，继续判断和推进。</p></div><div class="row">${btn('整理最新简报','xp-brief','refresh','soft')}<a class="btn" href="#automations">${i('clock')}定时规则</a></div></div><div class="xp-source-notice">当前投递到应用内；简报依据本地记录整理，定时内容由配置的模型准备。页面打开时检查，不向客户自动发送。</div><div class="xp-inbox-toolbar"><div class="ux-filter">${[['inbox','收件箱'],['unread','未读'],['failure','需要处理'],['archive','已归档']].map(([id,label])=>`<button data-act="xp-mail-filter" data-id="${id}" aria-pressed="${filter===id}">${label}${id==='unread'?' · '+all.filter(d=>!d.read&&!d.archived).length:''}</button>`).join('')}</div>${marketSelect()}</div><div class="xp-inbox"><section class="xp-mail-list" aria-label="来信列表">${list.map(d=>`<button data-act="xp-delivery" data-id="${d.id}" class="${current?.id===d.id?'selected':''} ${d.read?'':'unread'}"><div class="row between"><span>${d.kind==='failure'?'需要处理':d.kind==='brief'?'工作简报':'成果已备好'}</span><small>${stamp(d.at)}</small></div><h3>${esc(d.title)}</h3><p>${esc(d.preview)}</p><small>${esc(d.source)}</small></button>`).join('')||'<div class="xp-empty"><h3>这里还没有来信</h3><p>可以整理一份最新简报，或配置定时任务。</p></div>'}</section>${current?deliveryBody(current):'<div class="xp-empty xp-mail-placeholder">'+i('mail')+'<h2>选一封来信，查看已经准备好的工作</h2><p>阅读、回到工作台修改，或完成后归档。</p></div>'}</div>`;
  }
  function ecosystem(){
    const selected=ui().ecosystemTab||'data';
    const nav=`<nav class="ux-tabs" aria-label="生态配置">${[['data','数据源'],['plugins','插件'],['skills','Skills'],['mcp','MCP 服务']].map(([id,label])=>`<button data-act="xp-ecosystem-tab" data-id="${id}" aria-pressed="${selected===id}">${label}</button>`).join('')}</nav>`;
    let body='';
    if(selected==='data')body=`<div class="xp-ecosystem-data">${api.connections()}</div>`;
    if(selected==='plugins')body=`<p class="xp-source-notice">本地能力可直接打开使用。第三方插件安装与服务端运行环境尚未接入。</p><div class="xp-workflows">${[['poster','营销海报','从活动方案生成并编辑海报，导出 SVG / PNG。','campaigns','megaphone'],['quote','车源与费用','匹配同市场车型，试算报价和月供。','inventory','car'],['profile','客户画像','从销售对话中提取需求，核对后积累客户记忆。','customers','users']].map(([id,title,desc,page,icon])=>`<article class="xp-workflow"><div class="row between"><span class="xp-symbol">${i(icon)}</span><span class="badge green">内置可用</span></div><h3>${title}</h3><p>${desc}</p><a class="btn sm" href="#${page}">打开使用 ${i('arrow')}</a></article>`).join('')}</div>`;
    if(selected==='skills')body=`<p class="xp-source-notice">Skill 定义专业工作的步骤与交付要求。这里的配置会用于新建工作流；已有任务保留创建时的要求。</p><div class="xp-skill-list">${WORKFLOWS.map(w=>{const cfg=state().ecosystem.skills[w.id];return `<article><span class="xp-symbol">${i(w.icon)}</span><div><strong>${w.title}</strong><p>${PERSONAS[w.role].label} · ${w.output}</p><small>${cfg?.instruction?'含自定义工作要求':'内置工作方法'}</small></div><span class="badge ${cfg?.enabled===false?'gray':'green'}">${cfg?.enabled===false?'已停用':'已启用'}</span>${btn('配置','xp-skill',null,'sm',`data-id="${w.id}"`)}</article>`;}).join('')}</div>`;
    if(selected==='mcp')body=`<div class="xp-section-head"><div><h2>连接专业软件的工具与数据</h2><p>记录服务地址与只读范围，待服务端接入和测试。</p></div>${btn('添加 MCP 服务','xp-mcp','plus','primary')}</div><div class="xp-source-notice">保存配置不会建立连接。当前尚无可调用的外部 MCP 服务；认证凭据需要在服务端配置。</div><div class="xp-skill-list">${state().ecosystem.mcp.map(m=>`<article><span class="xp-symbol">${i('link')}</span><div><strong>${esc(m.name)}</strong><p>${esc(m.endpoint)}</p><small>${esc(m.scope)}</small></div><span class="badge gray">已配置 · 未连接</span>${btn('移除配置','xp-mcp-remove',null,'sm',`data-id="${m.id}"`)}</article>`).join('')||'<div class="xp-empty"><h3>添加 CRM、DMS 或品牌知识服务</h3><p>销售用客户记录，市场用品牌与活动数据，区域经理用门店经营数据。</p></div>'}</div>`;
    return `<div class="page-heading"><div><span class="eyebrow">ECOSYSTEM</span><h1>生态</h1><p>连接业务资料，配置专业方法，扩展 Cowork 的工作能力。</p></div><a class="btn" href="#knowledge">${i('book')}品牌与知识</a></div>${nav}${body}`;
  }
  function showWorkflow(id,data={}){
    const w=WORKFLOWS.find(w=>w.id===id);if(!w)return;
    if(state().ecosystem.skills[id]?.enabled===false){api.toast('这个工作流的 Skill 已停用，可在生态中重新启用。');return;}
    const customer=w.scope==='customer';
    api.showModal(w.title,`${w.output} · ${PERSONAS[w.role].label}`,`<div class="xp-flow-steps">${w.steps.map((s,n)=>`<span><b>${n+1}</b>${s}</span>`).join('')}</div><form id="xp-workflow-form" data-id="${w.id}"><label class="field-label" for="xp-subject">${customer?'选择客户':'选择市场资料'}</label><select class="field" id="xp-subject" name="subject" required><option value="">请选择</option>${customer?state().customers.filter(c=>ui().market==='all'||c.market===ui().market).map(c=>`<option value="${c.id}" ${data.customer===c.id?'selected':''}>${esc(c.name)} · ${esc(c.contact||c.vehicle)}</option>`).join(''):Object.entries(markets).filter(([id])=>id!=='all').map(([id,label])=>`<option value="store:${id}" ${(data.market||ui().market)===id?'selected':''}>${label}</option>`).join('')}</select>${customer?'<p class="xp-data-note">新客户可以先登记电话号码和已有信息。</p>'+btn('新增销售线索','ux-lead','plus','sm'):''}<label class="field-label" for="xp-goal">补充工作要求（选填）</label><textarea class="field" id="xp-goal" name="goal" maxlength="1500" placeholder="目标、期限、渠道或这次最需要解决的问题"></textarea><p class="xp-data-note">打开工作台后，可在右侧继续补充并发送给 Cowork。</p></form>`,`${btn('取消','close-modal')}<button class="btn primary" type="submit" form="xp-workflow-form">进入工作台 ${i('arrow')}</button>`);
  }
  function handleAction(act,data={}){
    if(!act.startsWith('xp-'))return false;
    if(act==='xp-workflow')showWorkflow(data.id,data);
    if(act==='xp-regional')api.navigate('regional');
    if(act==='xp-delivery'){const d=visibleDeliveries(state(),ui().role).find(d=>d.id===data.id);if(d){updateDelivery(state(),d.id,'read');ui().deliveryId=d.id;ui().deliveryFilter=d.archived?'archive':'inbox';api.save();api.navigate('proactive');}}
    if(act==='xp-mail-state'){updateDelivery(state(),data.id,data.mode);api.save();api.render();}
    if(act==='xp-mail-filter'){ui().deliveryFilter=data.id;ui().deliveryId=null;api.render();}
    if(act==='xp-brief'){const d=prepareBriefing(state(),ui().role,ui().market,new Date(),true);ui().deliveryId=d.id;ui().deliveryFilter='inbox';d.read=true;api.save();api.navigate('proactive');api.toast('最新工作区简报已整理好。');}
    if(act==='xp-delivery-work'){const d=state().deliveries.find(d=>d.id===data.id);if(d?.taskId)api.openGeneration(d.taskId);else if(d){const id=ui().role==='sales'?'lead':ui().role==='marketing'?'campaign-review':'store-action';showWorkflow(id);}}
    if(act==='xp-ecosystem-tab'){ui().ecosystemTab=data.id;api.render();}
    if(act==='xp-skill'){
      const w=WORKFLOWS.find(w=>w.id===data.id);if(!w)return true;const cfg=state().ecosystem.skills[w.id];
      api.showModal(w.title,'配置专业工作方法',`<form id="xp-skill-form" data-id="${w.id}"><label class="checkbox"><input type="checkbox" name="enabled" ${cfg?.enabled===false?'':'checked'}>启用该工作流</label><p class="xp-source-notice">${esc(w.prompt)}</p><label class="field-label" for="xp-instruction">门店专属要求（选填）</label><textarea class="field" name="instruction" id="xp-instruction" maxlength="1800" placeholder="例如：每份方案都列出待核实价格及负责核实的岗位。">${esc(cfg?.instruction||'')}</textarea></form>`,`${btn('取消','close-modal')}<button class="btn primary" form="xp-skill-form" type="submit">保存配置</button>`);
    }
    if(act==='xp-mcp')api.showModal('添加 MCP 服务','保存接入配置',`<form id="xp-mcp-form"><label class="field-label" for="xp-mcp-name">服务名称</label><input class="field" name="name" id="xp-mcp-name" required maxlength="100" placeholder="Toyota 门店 CRM"><label class="field-label" for="xp-mcp-endpoint">HTTPS 服务地址</label><input class="field" type="url" name="endpoint" id="xp-mcp-endpoint" required placeholder="https://your-service.example/mcp"><label class="field-label" for="xp-mcp-scope">只读数据范围</label><textarea class="field" name="scope" id="xp-mcp-scope" required maxlength="1000" placeholder="允许读取的门店、记录类型和用途"></textarea><p class="xp-data-note">不要填写密码或令牌。保存后仍需服务端接入与连接测试。</p></form>`,`${btn('取消','close-modal')}<button class="btn primary" form="xp-mcp-form" type="submit">保存配置</button>`);
    if(act==='xp-mcp-remove'){state().ecosystem.mcp=state().ecosystem.mcp.filter(m=>m.id!==data.id);api.save();api.render();}
    return true;
  }
  function submit(form,data){
    if(!form.id.startsWith('xp-'))return false;
    try{
      if(form.id==='xp-workflow-form'){
        const w=WORKFLOWS.find(w=>w.id===form.dataset.id);if(!w||state().ecosystem.skills[w.id]?.enabled===false)throw new Error('工作流不可用，请检查 Skill 配置。');
        const valid=w.scope==='customer'?state().customers.some(c=>c.id===data.subject):/^store:(US|AE|GB|DE)$/.test(data.subject);if(!valid)throw new Error('请先选择具体客户或市场。');
        const instruction=state().ecosystem.skills[w.id]?.instruction||'';
        const prompt=[w.prompt,instruction&&'门店工作要求：'+instruction,data.goal?.trim()&&'本次补充：'+data.goal.trim()].filter(Boolean).join('\n\n');
        api.closeModal();const chat=api.newTask(prompt,data.subject);Object.assign(chat,{persona:w.role,workflowId:w.id,title:w.title,goal:w.output,workflowSteps:w.steps,skillSnapshot:instruction});api.save();api.render();
      }
      if(form.id==='xp-skill-form'){if(!WORKFLOWS.some(w=>w.id===form.dataset.id))throw new Error('工作流不存在。');if((data.instruction||'').length>1800)throw new Error('工作要求不能超过 1800 字。');state().ecosystem.skills[form.dataset.id]={enabled:!!data.enabled,instruction:(data.instruction||'').trim(),updatedAt:new Date().toISOString()};api.save();api.closeModal();api.render();}
      if(form.id==='xp-mcp-form'){saveMCPConfiguration(state(),data);api.save();api.closeModal();api.render();api.toast('配置已保存，MCP 服务尚未连接。');}
    }catch(error){api.toast(error.message);}
    return true;
  }
  return {rolePicker,tabs,home,desk,regional,proactive,ecosystem,handleAction,submit};
}
